import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Tailwind & NextJS - Starter Template</title>
        <meta name="description" content="Generated By Next, Edited For Tailwind Start!" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ExampleComponent />

    </div>
  )
}

export default Home
